import React from "react";
import Navbar from "./Navbar";
import { Poppins } from "@next/font/google";
import Head from "next/head";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<>
            <Head>
                <title>Fire Market</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
			<header className={poppins.className}>
				<Navbar />
			</header>
			<main className={poppins.className}>
				{ children }
			</main>
		</>
	);
};

export default Layout;
