import Head from 'next/head'
import { Poppins } from '@next/font/google'
import { Hero, Navbar } from './components'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"]
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Fire Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className={poppins.className}>
        <div className='text-2xl font-bold text-center'>
          <Hero />
        </div>
      </main>
    </>
  )
}
